[tool.poetry]
name = "curso-streamlit-crud"
version = "0.1.0"
description = ""
authors = ["Luciano Borba"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
